### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by turulix** [turulix/NotDankMemer#7]
* **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [ ] support request
  - [x] general improvement
 
Bot is spitting out a index out of bounds when just useing +play

**Comment by EikeSan** [comment]
@turulix When this happens?

**Comment by turulix** [comment]
Hey im allready sorry for all the spaghetticode in the project.

But when a user just types "+play" and nothing more it fails with a IndexOutOfBounds 
Also i noticed the bot needs to be connected to a MongoDB to run correctly. Wrongly labeled as the SQL part in the settings. It should look something like that
![image](https://user-images.githubusercontent.com/28957605/66245194-9c55c000-e70c-11e9-9c14-6542d238f37d.png)

Going to update it in the readme asap

**Comment by areebahmed04** [comment]
Hi @turulix I am working on this issue.

**Comment by turulix** [comment]
Fixed with #11
